### ISSUE TITLE
transparency support

### ISSUE THREAD

**Issue by mighty9245** [florentc/xob#13]
first of all, damn, xob is so incredible, i'm glad that i discovered it, thank you for your work!

can we have some love for transparency? i would like to define colors like `#rrggbbaa`

**Comment by jeffmhubbard** [comment]
If you're running compton/picom, thanks to 1cadc70, you can just it `xob` to your `opacity-rule`.

```
opacity-rule = [ "80:class_g *?= 'xob'" ];
```

**Comment by mighty9245** [comment]
well, i thought a little and decided that rgba support is an overkill for a thing that i want to do. my idea is simple: thin stripe at the bottom of the screen long as the screen width. i actually made it but the only thing i want to get rid of is background. so maybe it would be better to implement somehow either enabling only drawing of content (so padding, border and background becomes invisible no matter their width) or disabling drawing of background (so only background becomes invisible). i think it should be simpler to implement instead of rgba support.

@florentc, what do you think about it? should i edit my issue?

**Comment by tobimensch** [comment]
I want transparancy also!

**Comment by loki7990** [comment]
@jeffmhubbard Strange, that doesn't work for me, neither does setting it to `80:class_i`

**Comment by jeffmhubbard** [comment]
@loki7990 Hmm, for me it just worked as expected after finding the class name. Here's my [picom.conf](https://raw.githubusercontent.com/jeffmhubbard/dotfiles/main/.config/picom/picom.conf) and [styles.cfg](https://raw.githubusercontent.com/jeffmhubbard/dotfiles/main/.config/xob/styles.cfg).

**Comment by loki7990** [comment]
Oof, I was using too small of an opacity change to notice (90%). Changing
it to something like 50% made it obvious it was transparent. My bad!

**Comment by florentc** [comment]
Now implemented thanks to @Hattshire's hard work.
