### ISSUE TITLE
weird behavior on decimals

### ISSUE THREAD

**Issue by mighty9245** [florentc/xob#14]
i created a named pipe (`mkfifo xob`) and played with it a little and here is what i noticed:
```
$ echo 3.14 > xob
Update: 3/100
$ echo 3.15 > xob
Update: 14/100
Update: 3/100
$ echo 4 > xob
Update: 15/100
Update: 4/100
```
basically, if you pass `a.b` to xob, it will parse only `a`, then if you pass other number, it will firstly parse `b` then your new number. i don't really see any flickering but i suspect that because of this issue bar get drawn twice and that's bad for performance and battery life.

**Comment by florentc** [comment]
Hello,

xob only expects to read integer values from the standard input. This is specified in the manpage but not in README.md. Sorry for the misunderstanding.

In your example, it seems you want to be able to input values with 2 decimal digits, between 0 and 100. That is 100*100=10000 possible values. Therefore, you will achieve the desired result by setting the number of steps (`-m`) to 10000 and multiplying your input values by 100.

**Comment by mighty9245** [comment]
oh, ok

but still, how it works? i mean isn't it strange that decimal values are kept somewhere somehow? this could be expected behavior:
```
> 3.14
< 3
---
> 4.15
< 4
```

but this what we actually have
```
> 3.14
< 3
---
> 4.15
< 14
< 4
```

actually i thought about editing value before passing it to the xob pipe (grep, sed, bc, whatever), but i thought it would be a performance hit since initially i wanted to change brightness/volume with 1% accuracy but now i switched to 10% accuracy and performance is not a problem anymore and i can manipulate values before passing them to xob easily
