### ISSUE TITLE
Behaves wierd on one Mashine

### ISSUE THREAD

**Issue by Tunfisch96** [florentc/xob#21]
Ive tried to install xob on my Second system.
I am able to make and make install but compared to my main system I get 
`src/main.c: In function ‘main’:
src/main.c:40:54: warning: comparison is always true due to limited range of data type [-Wtype-limits]
     while ((opt = getopt(argc, argv, "m:t:c:s:qvh")) != -1)`
after make.
When I run xob, I allways get just the output  if I had inserted a wrong Argument, the Bar does also never is visible.

**Comment by florentc** [comment]
Hello,

Thank you for this report and sorry for the inconvenience. It is possible that `char` is unsigned by default on your configuration.

In `main.c`, could you try changing `char opt;` line 39 to `signed char opt;`, compile xob again, and see if the warning and bug are solved?

**Comment by Tunfisch96** [comment]
Thank you that worked.
Is it possible to display the bar at the front display layer?
It works flawless until i connect to OpenAuto then the bar is behind the Openauto window.

**Comment by florentc** [comment]
The issue should be fixed now. Thank you for reporting.

Could you please open a new thread for your other issue?
