### ISSUE TITLE
pulse-volume-watcher.py script not working

### ISSUE THREAD

**Issue by Akmadan23** [florentc/xob#23]
OS: Fedora 32
WM: qtile

I installed the pulsectl package trough pip and I set the default pulse sink to 1 but the script is not working, any solutions? Thanks in advance

**Comment by Akmadan23** [comment]
Just found out that I just needed to restart the session

**Comment by Akmadan23** [comment]
I noticed that right after the start of a new session it works, but some minutes/hours later it don't, I can't understand the reason...

**Comment by florentc** [comment]
Sometimes, when connecting or disconnecting external HDMI or DisplayPort outputs that have their own audio output, or when using a bluetooth headset, the sink number can change and the script does not work anymore. When the problem occurs, can you confirm, using for example `pactl list sinks`, that the current sink number is the one in the script?

**Comment by Akmadan23** [comment]
I have manually set the default sink to 1 and even when the script stops working I checked it was still set to 1...

**Comment by florentc** [comment]
Are the script and xob still running after the problem occurs? Can you find them in the list of current running processes?

**Comment by Akmadan23** [comment]
Yes, and if I manually kill both the script and xob and then I relaunch them, they don't work

**Comment by florentc** [comment]
After the problem occurs and you kill the script and xob, can you edit the sink number in the script (try 0, 1, 2, 3) and find a sink number that works?

**Comment by Akmadan23** [comment]
yes, but the active sink is still 1, and it does not work with none of those

**Comment by florentc** [comment]
Are you able to suspect or identify what might trigger the issue? Are there audio-related actions or events happening before it stops handling new events? Until we offer a better "ready to use" solution than the current imperfect script, I am leaving this issue open.

**Comment by Akmadan23** [comment]
I noticed that the problem occurs after the automatic screen deactivation for power saving, maybe there is some xorg or pulseaudio process being interrupted...

**Comment by florentc** [comment]
I imagine `thescript | xob` is launched by your window manager at startup. Could you launch it manually in a terminal instead so we can see the output of xob? By default, xob prints a message on the standard output after every value update. After the problem occurs, we could check whether xob stops receiving new updates or the bar somehow fails to be displayed on screen.

**Comment by Akmadan23** [comment]
Here is a screenshot, it is still running but it does not receive any signal
![xob](https://user-images.githubusercontent.com/49314270/97114177-38bf7b80-16ef-11eb-9cb8-bca574c79fa5.png)

**Comment by florentc** [comment]
Ok, then it means it is probably not a display issue after the screen leaves power savingg mode and turns back on, but rather some behavior with pulseaudio we fail to understand. I am sorry I am out of ideas for now. I am of course leaving the issue open in case you gather more details or someone else can help on the matter.

In the meantime you may switch to using a named pipe and have the updates triggered by keybindings although I admit this is less ideal.

Sorry for the inconvience. I hope we eventually sort this out.

**Comment by Akmadan23** [comment]
No problem, I understand it's weird, thank you for the support

**Comment by spurgelaurels** [comment]
Curious, I'm seeing similar behaviour, however only when I set the sink_id to anything above 1. 

I wonder if you explicitly set the sink_id to 0 if you'll see the same behaviour.

**Comment by daf** [comment]
For me, I noticed that the `sink_id` was being used as both a list index (into the list returned by `pulse.sink_list()`) as well as the `index` value assigned by pulseaudio to the sink itself.  On my system, these differed - I wanted the audio device that was first in the list of sinks but somehow had the pulseaudio "index" value of 3.

Could it be that those index values are changing, or the sink list order is re-arranging after some period, and therefore these don't line up anymore?

The script could probably be updated to only be keyed off the "index" value that pulseaudio knows about.

**Comment by florentc** [comment]
I merged the fix by @daf 
Can you confirm this solves the issue?

**Comment by Akmadan23** [comment]
Yes it works perfectly now, thank you very much
