### ISSUE TITLE
[Request] Rounded corners?

### ISSUE THREAD

**Issue by Barbarossa93** [florentc/xob#24]
Hello,

Thanks for making/sharing this software! It's definitely something I was looking for and have been using for a while now. I did have one request though. For each of the elements such as padding, border, margins, etc. it would be great to be able to define a radius to round the sharp corners. I know ibhagwan's fork of picom can round the outer most corners, but unfortunately it is unable to round the inner parts of xob.

**Comment by florentc** [comment]
Hello,

Thank you very much for your interest in xob and your suggestion. xob relies on xlib which only provides basic drawing features and is not well adapted to implementing nice-looking (antialiased) rounded corners. There is no plan to migrate to a higher level rendering library that would make it easy to implement rounded corners. In the near future, thanks to a major contribution that will be merged soon, xob will also rely (optionally) on the xrender extension to enable transparency. As far as I know, this light extension does not provide anything that would make the implementation of rounded corners easy either. I hope this is not a deal breaker for you and you will continue enjoying xob.

**Comment by Barbarossa93** [comment]
No worries, I didn't know what the limitations are for Xlib. For now, I'll
just strip down to a bare xob (no borders,paddings,outlines,etc.) and let
ibhagwan's fork of picom create the rounded corners. Although, I have one
possible idea... Maybe I could have two bars running at the same time but
have one be a few milliseconds behind the other to create faux rounded
corners for both the inner and outer parts? I'll tinker around and see what
I can come up with for those who stumble upon this issue
