### ISSUE TITLE
pulse-volume-watcher stopped working after update.

### ISSUE THREAD

**Issue by agoodfellow123** [florentc/xob#26]
Hello there, im using the pulse-volume-watcher script. It used to work perfectly until last update. right now xob doesn't launch and when I try to launch it manually with "~/.config/xob/pulse-volume-watcher.py | xob" it gives me the following error:
```
[1] 125941 125942
Info: reading configuration from /home/alova/.config/xob/styles.cfg.Traceback (most recent call last):  File "/home/alova/.config/xob/pulse-volume-watcher.py", line 2, in <module>
    from pulsectl import Pulse, PulseLoopStop
ModuleNotFoundError: No module named 'pulsectl'
[1]  + 125941 exit 1     ~/.config/xob/pulse-volume-watcher.py |
       125942 done       xob
```

**Comment by florentc** [comment]
Hello,

Are you talking about an update in your OS? There hasn't been any recent update of the example script in the README.

The script requires the pulsectl python library and it cannot be found, according to the error message. Could you please check if it is installed (either as a package in your distribution or a python package manager). It is possible the python library was a dependency of a package on your system that no longer relies on it and it has been removed. The pulsectl library is not an xob dependency. Therefore you might have to manually install it.

**Comment by agoodfellow123** [comment]
Yes i was talking about my os update, its arch based so this kind of things getting broken is nothing new. I just checked the python-pulsectl package and it is still installed. Last update was six months ago. So I'm really out of ideas on this one.

**Comment by florentc** [comment]
On my arch install, with a full update a few minutes ago, and python-pulsectl 20.6.0 installed from the AUR, the script still works (I am using xob and the script daily). Do you have the latest python-pulsectl?

**Comment by agoodfellow123** [comment]
Yes, the same version.

**Comment by florentc** [comment]
I am also out of ideas. We have matching configurations.

**Comment by agoodfellow123** [comment]
Got it, i'll let you know if anything changes.

**Comment by agoodfellow123** [comment]
Redownloading python-pulsectl fixed it. Don't know the reason though.

**Comment by florentc** [comment]
Great! This is weird indeed. Thank you this may help other users who encounter a similar issue.

**Comment by themdiffs** [comment]
So redownloading pulsectl isn't exactly an option when using nix, so xob just doesn't work for nixos without the fallback method.
