### ISSUE TITLE
WM_CLASS is unset

### ISSUE THREAD

**Issue by rehashedsalt** [florentc/xob#3]
Pretty simple: the bar has no [`WM_CLASS`](https://tronche.com/gui/x/icccm/sec-4.html#WM_CLASS) (at least according to a cursory `xprop`). Setting one will allow for better cooperation with the WM and simpler configuration with other programs (Compton especially comes to mind).

I'm no X wizard, but it looks like all you need to do is make a call to XSetClassHint[(3)](https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-class.html). Assuming that you can't just bundle this into an existing call, that is.

**Comment by florentc** [comment]
Thank you, this is done.
