### ISSUE TITLE
I created ~/.config/xob/styles.cfg and edited it, yet the appearance of xob did not change

### ISSUE THREAD

**Issue by Raytle** [florentc/xob#32]
After reading [Appearance](https://github.com/florentc/xob#appearance) I created `~/.config/xob/styles.cfg` as shown here...

![Image 1](https://user-images.githubusercontent.com/81956552/125989024-71e888e6-3bdf-42e9-b1dd-b58c93ec35f5.png)

Then I edited `~/.config/xob/styles.cfg` in the following manner...
![Image 1](https://user-images.githubusercontent.com/81956552/125989703-d5a8dd30-2ac4-4208-a111-b2603bedaa90.png)

yet the appearance of xob did **not** change.

By the way, I had heard of "man pages" (manual pages), and perhaps even opened a couple in the past but I needed to search on Google to find [How to Easily Read a Linux Man Page](https://www.maketecheasier.com/read-linux-man-page/). Based on reading that, I entered `whatis xob` and `man xob` but I didn't find the manual page ("man page") for xob.

I read [Where should the XDG_CONFIG_HOME variable be defined?](https://superuser.com/a/365918) but I'd rather use `~/.config/xob/styles.cfg` to change the appearance of xob because I am comfortable with putting my configuration files in `~/.config/`.

**Comment by MuhammedZakir** [comment]
xob won't reload itself when config changes. You will have to restart it yourself (quit it and start it).

> I entered `whatis xob` and `man xob` but I didn't find the manual page ("man page") for xob.

Because you haven't installed xob globally <sup>[1]</sup>, `man` won't be able to find the manpage of xob. To do that, you will have to pass the path of the manpage you wanna read. In your case, `man "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/doc/xob.1"`.

If you don't want to install it to `/usr/bin/` or `/usr/loca/bin/`, you can use `~/.local/bin`.

[1] Actually, not in your "PATH". See http://www.linfo.org/path_env_var.html.

**Comment by Raytle** [comment]
> xob won't reload itself when config changes. You will have to restart it yourself (quit it and start it again).

Thanks for letting me know. 

Actually I had presumed that to be the case. Therefore, prior to posting this issue I had rebooted my machine. Nonetheless, as I indicated in my penultimate comment (which is also the first comment in this issue)—"the appearance of xob did **not** change."

>> I entered whatis xob and man xob but I didn't find the manual page ("man page") for xob.

> Because you haven't installed xob globally [1], man won't be able to find the manpage of xob. To do that, you will have to pass the path of the manpage you wanna read. In your case, man "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/doc/xob.1".

> If you don't want to install xob to /usr/bin/ or /usr/loca/bin/, you can use ~/.local/bin.

> [1] Actually, not in your "PATH". See http://www.linfo.org/path_env_var.html.

Thanks for letting me know. I appreciate that. I can do what you indicated but probably won't merely to read the xob manual page. What I was gently implying was that the information in the xob manual page should be added to this Github project but now I will be blunt: please add the xob manual page to this Github project. 

I am not being snarky in the least, but it seems to me that it is utterly, totally, and completely ridiculous to explain to users that they can install xob "non-globally" (I guess, "locally") yet then require them to install xob globally merely to read the manual page. Furthermore, many projects on Github either include the documentation directly on Github or a link to the documentation on a site such as https://readthedocs.io/.

**Comment by Raytle** [comment]
> > Actually I had presumed that to be the case. Therefore, prior to posting this issue I had rebooted my machine. Nonetheless, as I indicated in my penultimate comment (which is also the first comment in this issue)—"the appearance of xob did **not** change."
> 
> Color values are written using hexadecimal values (1-9, a-f). You used `rrrrrr`, which is an invalid color, and xob uses default config in such cases. If you run xob in a terminal, it will throw an error.
> 
> 1. https://www.w3schools.com/colors/colors_hexadecimal.asp
> 2. https://www.w3schools.com/colors/colors_picker.asp

**Thank you! That solved my problem.** I certainly made a mistake by typing in `rrrrrr`. I actually know what hexadecimal is (it's base 16) but I failed to think about that when I typed in the letters. Yeah, I should have typed in a combination of the following letters and numbers **1-9, a-f**. I'm sorry for making a hasty oversight.

 
> Also, you can run more than one xob at a time.

Thanks for letting me know. 

> So when you want to test your config, just run xob in a terminal.

Are you implicitly suggesting I do this to avoid needing to reboot my computer when I want to see how changes I have made to `/home/y/.config/xob/styles.cfg` will appear the next time I reboot my computer? If so, I would appreciate you providing me the code I should run in a terminal to see how changes I will have made to `/home/y/.config/xob/styles.cfg` will appear without requiring me to reboot my computer.

> Preferably, with a longer timeout (`-t` option), so, for exmaple, you can switch to other apps or workspaces to see if it fits nicely.

Thanks for letting me know.

Now that we are on the subject, I read but did not understand how to implement [Usage](https://github.com/florentc/xob#usage) by which I mean this..

![Image 1](https://user-images.githubusercontent.com/81956552/126001697-6d38a953-409c-4339-bc7c-73baa0cdcf25.png)

I have this script automatically run when I start my machine...

`tail --follow "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/named_pipe_from_amixer_to_xob" | "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/xob"`

Furthermore, I have...

`pactl set-sink-volume @DEFAULT_SINK@ +10% && amixer -D pulse sset Master unmute && amixer -c 1 -M -D pulse get Master | grep -o -E '[[:digit:]]+%' >> "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/named_pipe_from_amixer_to_xob"` bound to `F10`,

and...

`pactl set-sink-volume @DEFAULT_SINK@ -10% && amixer -D pulse sset Master unmute && amixer -c 1 -M -D pulse get Master | grep -o -E '[[:digit:]]+%' >> "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/named_pipe_from_amixer_to_xob"` bound to `F9`.

I would like to change the maximum value/number of steps in the bar to, for example, 500; the duration that the bar remains on-screen after an update to, say, 2000 milliseconds; and the path to, for example, /`home/y/.config/xob/styles.cfg`. How would I accomplish those steps?

In addition, how would I add a second (and third, and fourth) style to, and how would I choose a second (or third, or fourth) style from, for example, /`home/y/.config/xob/styles.cfg` which currently contains...

```
default = {
    x         = {relative = 1; offset = -48;};
    y         = {relative = 0.5; offset = 0;};
    length    = {relative = 0.3; offset = 0;};
    thickness = 24;
    outline   = 3;
    border    = 4;
    padding   = 3;
    orientation = "vertical";

    overflow = "proportional";

    color = {
        normal = {
            fg     = "#6f98a0";
            bg     = "#111111";
            border = "#ffffff";
        };
        alt = {
            fg     = "#4b64f3";
            bg     = "#000000";
            border = "##4b64f3";
        };
        overflow = {
            fg     = "#ff0000";
            bg     = "#000000";
            border = "#ff0000";
        };
        altoverflow = {
            fg     = "#550000";
            bg     = "#000000";
            border = "#550000";
        };
    };
};
```

Would the following syntax be correct for adding a style I have included below named, **"alternate_style_01"** ?...

```
default = {
    x         = {relative = 1; offset = -48;};
    y         = {relative = 0.5; offset = 0;};
    length    = {relative = 0.3; offset = 0;};
    thickness = 24;
    outline   = 3;
    border    = 4;
    padding   = 3;
    orientation = "vertical";

    overflow = "proportional";

    color = {
        normal = {
            fg     = "#6f98a0";
            bg     = "#111111";
            border = "#ffffff";
        };
        alt = {
            fg     = "#4b64f3";
            bg     = "#000000";
            border = "##4b64f3";
        };
        overflow = {
            fg     = "#ff0000";
            bg     = "#000000";
            border = "#ff0000";
        };
        altoverflow = {
            fg     = "#550000";
            bg     = "#000000";
            border = "#550000";
        };
alternate_style_01 = {
    x         = {relative = 1; offset = -48;};
    y         = {relative = 0.5; offset = 0;};
    length    = {relative = 0.3; offset = 0;};
    thickness = 24;
    outline   = 3;
    border    = 4;
    padding   = 3;
    orientation = "vertical";

    overflow = "proportional";

    color = {
        normal = {
            fg     = "#2b71c4";
            bg     = "#111111";
            border = "#2b71c4";
        };
        alt = {
            fg     = "#92c13d1";
            bg     = "#000000";
            border = "#92c13d1";
        };
        overflow = {
            fg     = "#ff0000";
            bg     = "#000000";
            border = "#ff0000";
        };
        altoverflow = {
            fg     = "#290000";
            bg     = "#000000";
            border = "#5290000";
        };
    };
};
```

> There is a markdown file in xob's `doc` dir (same content as manpage). You can open it locally, or https://github.com/florentc/xob/blob/master/doc/xob.md. 

Thanks for the information. I just opened it and glanced at it.

> Frankly, if you are going to read like that, README.md is better. It explains everything in detail. Manpages are generally a condensed reference manual, mostly for quick-look.

Sure. That makes sense. To me manual pages are for "techies" and  documentation is for "non-techies." Therefore, I generally eschew manual pages ("man pages") in favor of documentation ("the docs"). 

> Edit: what I am mean is that the readme file is the detailed manual, and manpage is the reference manual.

Thanks for taking the time to clarify that me. I appreciate that.

In case you were wondering, I didn't randomly choose to look for the xob manual page. Rather, based on this explicit instruction, "**Consult the man page** for detailed information about the configuration file and the available options", I, well, ummm, yeah, I consulted the xob manual page. Please see below...

![Image 1](https://user-images.githubusercontent.com/81956552/126000632-9a200a0f-8b53-4ad5-b1ad-c9b8b29c56c5.png)

**Comment by MuhammedZakir** [comment]
You're welcome! :-)

> > So when you want to test your config, just run xob in a terminal.
> 
> Are you implicitly suggesting I do this to avoid needing to reboot my computer when I want to see how changes I have made to `/home/y/.config/xob/styles.cfg` will appear the next time I reboot my computer?

Yes. You never need to reboot your computer to reload the config. Just quit the currently running xob, and start it again. 

> If so, I would appreciate you providing me the code I should run in a terminal to see how changes I will have made to `/home/y/.config/xob/styles.cfg` will appear without requiring me to reboot my computer.

You can run xob in a terminal, and then type some (integer) values and press enter/return. It will show the bar. If you want to quit it, type any non-integer values and press enter. You will have to quit and start it again each time you change the config. There is currently no way to "hot-reload" the config.

> I have this script automatically run when I start my machine...
> 
> `tail --follow "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/named_pipe_from_amixer_to_xob" | "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/xob"`
>  *--snip--*
> I would like to change the maximum value/number of steps in the bar to, for example, 500; the duration that the bar remains on-screen after an update to, say, 2000 milliseconds; and the path to, for example, /`home/y/.config/xob/styles.cfg`. How would I accomplish those steps?

```
tail --follow "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/named_pipe_from_amixer_to_xob" | "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/xob -m 500 -t 2000 -c /home/y/.config/xob/styles.cfg"
```

In manpages, flags/options inside square brackets(`[]`) are optional. If something is inside "less than" and "greater than" symbols (`<>`), then it is a placeholder and should be replaced (incl. `<>`) with appropriate value. These are some conventions and not everyone follow them. Especially, the second one (`<>`) - it is only used if you want to make the placeholder explicit, for example when there are lot of options (e.g. git).

> In addition, how would I add a second (and third, and fourth) style to, and how would I choose a second (or third, or fourth) style from, for example, /`home/y/.config/xob/styles.cfg` which currently contains... 
> *--snip--*
> Would the following syntax be correct for adding a style I have included below named, **"alternate_style_01"** ?...

Almost. You put `alternative_style_01` inside `default`. That's wrong. Each style should be seperate.

> ```
> default = {
>     x         = {relative = 1; offset = -48;};
>     y         = {relative = 0.5; offset = 0;};
>     length    = {relative = 0.3; offset = 0;};
>     thickness = 24;
>     outline   = 3;
>     border    = 4;
>     padding   = 3;
>     orientation = "vertical";
> 
>     overflow = "proportional";
> 
>     color = {
>         --snip--
>     };
> };
>
> alternate_style_01 = {
>     x         = {relative = 1; offset = -48;};
>     y         = {relative = 0.5; offset = 0;};
>     length    = {relative = 0.3; offset = 0;};
>     thickness = 24;
>     outline   = 3;
>     border    = 4;
>     padding   = 3;
>     orientation = "vertical";
> 
>     overflow = "proportional";
> 
>     color = {
>        --snip--
>     };
> };
> ```

See the first question in FAQ [1]. It shows defining two styles, "volume" and "backlight". Then if you want to use style "backlight", you would specify it using `-s` option when running

```
/path/to/xob -s backlight
```
```
tail -f /path/to/named_pipe | /path/to/xob -s backlight
```

[1] https://github.com/florentc/xob#faq

**Comment by MuhammedZakir** [comment]
Another thing to note is that you will have to run seperate xob for each style and so, need seperate named pipe (if that's what your're using).

**Comment by florentc** [comment]
I am closing this issue: xob only reads the configuration file at startup. After changes are made to the configuration file, only new xob instances will take the changes into account so you have to restart the program. Discussions about a possible hot-reloading feature are in #33.

**Comment by Raytle** [comment]
Thanks for letting me know.

**Comment by Raytle** [comment]
> > > So when you want to test your config, just run xob in a terminal.
> > 
> > 
> > Are you implicitly suggesting I do this to avoid needing to reboot my computer when I want to see how changes I have made to `/home/y/.config/xob/styles.cfg` will appear the next time I reboot my computer?
> 
> Yes. You never need to reboot your computer to reload the config. Just quit the currently running xob, and start it again.


Ok. Good. Thanks for letting me know. I appreciate that.
 


> > If so, I would appreciate you providing me the code I should run in a terminal to see how changes I will have made to `/home/y/.config/xob/styles.cfg` will appear without requiring me to reboot my computer.
> 
> You can run xob in a terminal, and then type some (integer) values and press enter/return. It will show the bar. If you want to quit it, type any non-integer values and press enter. You will have to quit and start it again each time you change the config.

I see.

>  There is currently no way to "hot-reload" the config.

I see. That would be a nice feature.


> > I have this script automatically run when I start my machine...
> > `tail --follow "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/named_pipe_from_amixer_to_xob" | "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/xob"`
> > _--snip--_
> > I would like to change the maximum value/number of steps in the bar to, for example, 500; the duration that the bar remains on-screen after an update to, say, 2000 milliseconds; and the path to, for example, /`home/y/.config/xob/styles.cfg`. How would I accomplish those steps?
> 
> ```
> tail --follow "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/named_pipe_from_amixer_to_xob" | "/home/y/Xob overlay volume bar for Lubuntu/xob-0.2/xob" -m 500 -t 2000 -c /home/y/.config/xob/styles.cfg
> ```

Thank you! That was very helpful to me!


> Edit: Note that you don't have to specify config in when running xob as long you use a default path. See https://github.com/florentc/xob/blob/master/doc/xob.md#configuration-file.

Ok. I understand.
 

> In manpages, flags/options inside square brackets(`[]`) are optional. If something is inside "less than" and "greater than" symbols (`<>`), then it is a placeholder and should be replaced (incl. `<>`) with appropriate value. These are some conventions and not everyone follow them. Especially, the second one (`<>`) - it is only used if you want to make the placeholder explicit, for example when there are lot of options (e.g. git).

Thanks for taking the time to explain that to me.


> > In addition, how would I add a second (and third, and fourth) style to, and how would I choose a second (or third, or fourth) style from, for example, /`home/y/.config/xob/styles.cfg` which currently contains...
> > _--snip--_
> > Would the following syntax be correct for adding a style I have included below named, **"alternate_style_01"** ?...
> 
> Almost. You put `alternative_style_01` inside `default`. That's wrong. Each style should be seperate.

Ah! Ok. I see! 

> > ```
> > default = {
> >     x         = {relative = 1; offset = -48;};
> >     y         = {relative = 0.5; offset = 0;};
> >     length    = {relative = 0.3; offset = 0;};
> >     thickness = 24;
> >     outline   = 3;
> >     border    = 4;
> >     padding   = 3;
> >     orientation = "vertical";
> > 
> >     overflow = "proportional";
> > 
> >     color = {
> >         --snip--
> >     };
> > };
> > 
> > alternate_style_01 = {
> >     x         = {relative = 1; offset = -48;};
> >     y         = {relative = 0.5; offset = 0;};
> >     length    = {relative = 0.3; offset = 0;};
> >     thickness = 24;
> >     outline   = 3;
> >     border    = 4;
> >     padding   = 3;
> >     orientation = "vertical";
> > 
> >     overflow = "proportional";
> > 
> >     color = {
> >        --snip--
> >     };
> > };
> > ```
> 
> See the first question in FAQ [1]. It shows defining two styles, "volume" and "backlight". Then if you want to use style "backlight", you would specify it using `-s` option when running

Ok.
 
> ```
> /path/to/xob -s backlight
> ```
> 
> ```
> tail -f /path/to/named_pipe | /path/to/xob -s backlight
> ```
> 
> Note: default values are used for fields you omitted.
> 
> [1] https://github.com/florentc/xob#faq


Ok. Thanks.

**Comment by Raytle** [comment]
> Another thing to note is that you will have to run seperate xob for each style and so, need seperate named pipe (if that's what your're using).

Ah! Thanks you. Yes, that makes sense to me.

**Comment by Raytle** [comment]
Xob has been working flawlessly for me on Lubuntu 20.04 LTS. It's a pleasure to see  overlay volume bar when I press the hotkeys I have bound to increase and decrease the volume. Thanks for taking the time to patiently help me get it set up.
