### ISSUE TITLE
Configuration with Xresources?

### ISSUE THREAD

**Issue by Hugo-Heagren** [florentc/xob#49]
The man page says that there is a possible plan for configuration with Xresources. This would be really cool -- is it still a possibility?

**Comment by florentc** [comment]
Hello, sorry for the late reply. Unfortunately I no longer actively develop new features for `xob` (only bug fixes) as the world has mostly moved to Wayland and there is less popular and personal interest in the project. I am not opposed to merging the feature if somebody eventually submits a PR.
